---
# Project Information
site_name: Multi-target learning (MTL)
site_author: Panos Kazantzis
site_description: Python package for Multi-target Learning (MTL), performing simultaneous prediction of multiple dependent variables and evaluating results

# Repository information
repo_name: panoskazantzis/multi-target-learning-MTL
repo_url: https://github.com/panoskazantzis/multi-target-learning-MTL
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Panos Kazantzis

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/panoskazantzis
      name: panoskazantzis on GitHub

# Page tree
nav:
  - Home: index.md
